### ISSUE TITLE
NOTICE: Feathub no longer in use.

### ISSUE THREAD

**Issue by FrostTheFox** [RocketMap/RocketMap#1119]
Please use Github issues, with the [Feature Request] tag. It will be labeled accordingly. 

Any further cases where feathub is mentioned please let me know and I will update it accordingly.

**Comment by Becold** [comment]
Please, edit the (wiki page)[https://github.com/PokemonGoMap/PokemonGo-Map/wiki

**Comment by NoobDev3** [comment]
Done... I thought that would require a PR but it appears to have saved directly?

**Comment by FrostTheFox** [comment]
@NoobDev3 I have direct commit access, so I can just change it up directly.

@Becold Will do right now.

**Comment by Imoq** [comment]
@FrostTheFox : whenever you open a new issue, you still get this message in the template:

>  FOR FEATURE REQUESTS GO TO:
>   
>   http://feathub.com/PokemonGoMap/PokemonGo-Map/

**Comment by FrostTheFox** [comment]
@Imoq Will fix momentarily. Thanks.

**Comment by FrostTheFox** [comment]
Removed.

**Comment by sebastienvercammen** [comment]
@FrostTheFox, we should re-add the "FOR FEATURE REQUESTS" message w/ the devkat link, and close this issue. :)

**Comment by FrostTheFox** [comment]
@sebastienvercammen adding now

**Comment by FrostTheFox** [comment]
done
