### ISSUE TITLE
-ss duplicate scans, same location multiple times

### ISSUE THREAD

**Issue by Silvanus0** [RocketMap/RocketMap#989]
## Expected Behavior

The scans should go from one location to the next, and cycle through the list after a full hour
## Current Behavior

Certain locations are being scanned repeatedly over a short time. Sometimes twice in a row.
## Possible Solution

Keep a history of when a spawn point was scanned and dont scan if not enough time has passed. Alternatively sort through DB to eliminate random spawn times giving duplicates
## Steps to Reproduce (for bugs)
1. DB of spawns with points that have some random times
2. start -ss
3. see workers search the same coordinates multiple times.
## Context

This increases the number of scans/requires up to 2x the number of workers for the same area due to wasted scans
## Your Environment

- Version used: node 4.4.7, npm 2.15.8
- Python 2.7, MySQL(mariadb-10.1.16-winx64)
- Windows 10

For example location (42.626893,-71.419129) is scanned 5 times in 21 seconds
![image](https://cloud.githubusercontent.com/assets/21208075/17980065/a6dfc810-6acb-11e6-85f6-0cacb33df7b2.png)

This is a seperate location showing some random spawn times. (normally it is XX:34:31)
"encounter_id"  "spawnpoint_id" "pokemon_id"    "latitude"  "longitude" "disappear_time"
"MTE4NzM0MDM4MzAzNTY2NjQ3MzM="  "89e3a4425ed"   "116"   "42.6446668494424"  "-71.3198535782298" "2016-08-19 02:34:31"
"NDk0MTY1OTYyOTU5MjE0MzI5Mw=="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 04:34:31"
"ODg4NzkxMDU1OTQzNjk4NTc0MQ=="  "89e3a4425ed"   "69"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 05:34:31"
"NDQ0NTc4MzU5NjM2MDkxMjIyMQ=="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 06:34:31"
"MTE4MTA5NTM5MjI5OTQ5NTgwNQ=="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 08:34:31"
"MTYzNzkzNzc4NTI5OTk0OTQ0Mjk="  "89e3a4425ed"   "90"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 10:20:22"
"MTc1NzMwNDMyMDMwNzI0MzU1NjU="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 11:34:31"
"MTI2MTg4MTM2MTM2MTE3OTE1ODE="  "89e3a4425ed"   "124"   "42.6446668494424"  "-71.3198535782298" "2016-08-19 14:22:40"
"MjczNzAwMTU4MDM4ODE1MTU5Nw=="  "89e3a4425ed"   "48"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 15:20:24"
"NzQ4ODAyOTg3ODU0MjkwMDQ3Nw=="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 16:34:23"
"MTIzODU5MDU5MjAyNDMyNjExMzM="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 17:34:21"
"MzcyNzQ2NTY0MTI1MjM1MDE0MQ=="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 20:20:24"
"NTg3Mjc1NjEwNTM5OTQ2NTEwMQ=="  "89e3a4425ed"   "116"   "42.6446668494424"  "-71.3198535782298" "2016-08-19 21:34:22"
"MTY0MTUyMDI3NTcxODkyMjk3NDE="  "89e3a4425ed"   "41"    "42.6446668494424"  "-71.3198535782298" "2016-08-19 23:34:22"
"NTI4MzM3MTgyOTMzODc3NzcwOQ=="  "89e3a4425ed"   "118"   "42.6446668494424"  "-71.3198535782298" "2016-08-20 03:34:22"
"OTQyNzEwNTAxMzk1NzYzNTA4NQ=="  "89e3a4425ed"   "46"    "42.6446668494424"  "-71.3198535782298" "2016-08-20 05:34:23"
"MTQ2MjQ5MDQ0NjMyNTYyMjI2ODU="  "89e3a4425ed"   "96"    "42.6446668494424"  "-71.3198535782298" "2016-08-20 06:34:24"
"ODYyMzg1NzI3NDc3ODEyNDI4NQ=="  "89e3a4425ed"   "41"    "42.6446668494424"  "-71.3198535782298" "2016-08-20 08:34:20"
"NTY2NjU0MDc3NDU4MjUxNjE3Mw=="  "89e3a4425ed"   "92"    "42.6446668494424"  "-71.3198535782298" "2016-08-20 09:34:22"
"MTA4NjQzNDAyMjU5NDY3NjUyMTM="  "89e3a4425ed"   "124"   "42.6446668494424"  "-71.3198535782298" "2016-08-20 10:34:23"

**Comment by TheNewDarkOne** [comment]
This is being caused by same bug causing this
https://github.com/PokemonGoMap/PokemonGo-Map/issues/939

Should be fixed by this pull request
https://github.com/PokemonGoMap/PokemonGo-Map/pull/986

**Comment by Silvanus0** [comment]
I had looked at that, but considering this is an issue of too MANY spawns instead of #939 having too FEW, I wasn't sure if it was related.

**Comment by Silvanus0** [comment]
I am new to this, but I applied the fix in #986 and I'm still getting duplicates. I think it could be a separate issue.

**Comment by TheNewDarkOne** [comment]
Good to know

**Comment by averylarry** [comment]
Do you use a spawnpoint file?  If so, have you regenerated it recently?  Can you look to see if there are duplicate entries in that file?

Note that I've never seen this behavior -- but I use very small areas.

**Comment by Silvanus0** [comment]
I do not use a spawnpoint file (I do -ss in beehive to cover a large area) I have been using the included full pogom database but with MySQL instead. I included an example of a duplicate I have in that file. It's an issue where about 1% of spawn points will start throwing out random despawn times (since about 8/19) and I think the program assumes they are each unique spawn data so it tries to scan it for every different time, even if they are only 1 sec apart. In the above example it shows the main spawn time of 34:31, but it also has (20:22, 20:24, 22:40, 34:20, 34:21, 34:22, 34:23, 34:24) so the program scans an additional 8 times (also I cut out data, it probably has another 20 times for that one spawnpoint)

In addition I have been running just -ss for a couple days, and every time I restart the workers I notice the spawnpoints steadily increasing (say about 10%/day) even after days of regular spawn point data collection. I assume it keeps finding more of these random spawns and making the issue worse.

If you would like me to include any files for analysis or to test something specifically let me know.

**Comment by Silvanus0** [comment]
It seems like PR #990 might provide a fix for this, if I have some time I'll see if I can figure out how to set that up and ill post the results.

**Comment by averylarry** [comment]
#990 (and other compression/clustering concepts) would only mask an underlying problem.  The code should not produce duplicates to begin with.
Some possibilities:
1)  An issue with MySQL.  The MySQL query is different from the sqlite query (uses 'distinct' instead of 'group_by').
2)  Bad data in the database -- who knows how.  Would have to clear the database to check (but of course, then you have to re-find all the spawnpoints).
3)  Bad time, whether current or when something was stored in the database.
4)  An issue with the searching and queues.  We have not verified if the issue is from duplicated spawnpoints or if the issue comes later with the overseer putting things into multiple queues.
5)  Other.

I guess you could start by dumping the spawnpoints to a .json file and seeing if there are duplicates there.  We would know if it's an issue with generating the list of spawnpoints or an issue with the overseer/queues/workers.

Also -- post the arguments you are running with.

**Comment by Silvanus0** [comment]
I agree #990 would mask it, but only if it is a client side issue. If the server is giving out random spawn times as it seems it is doing, then something like #990 would be required in order to deal with the extra data in a way that makes sense (assuming its not just me). If it matters, the random spawn times were not present in my database until 8/19, so if there was a code change it could stem from back then.

1) To be clear, the issue was present before I switched from SQLite to MySQL
2) Have not done this yet, but noted.

I'll check the spawn dump.

From batch: Beehive with -lp 3
%PythonPath% %Executable% -a %auth% -ss -u %username1% -p %password% -l "la, lo" -st 20 -ns -k %GAPI%

**Comment by BaIthamel** [comment]
This is probably related to the 595 hack.

**Comment by gabrielsoldani** [comment]
#990 and other spawnpoint compression/clustering proposals have nothing to do with this and are not the solution.

**Comment by Silvanus0** [comment]
Here is a small portion of my spawn data from spawn dump to .JSON. There are multiple entries per spawn id with varying time.


[spawn.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/441277/spawn.txt)

**Comment by Silvanus0** [comment]
I've done some more digging and I've noticed a potential issue with the get_spawnpoints, specifically when you query MySQL with .distinct. Its not handling it correctly. It should cut out all but unique spawnpoint_id's except its not limited to just that one column. It is actually checking for distinct rows and since most points would have identical rows across different times, the only ones not cut out are the bad ones with random times.

I think its a limitation with the distinct command. For example I tested between the current code, no distinct argument at all, and a blank query.distinct(). The current code and the blank return identical results for my sample, while no distinct check floods the table as expected.

So because of this there needs to be a more specific operation to remove extra entries of identical spawnpoint_id's. I'll look into it more and if I find the solution I'll make a PR, but I'm new to SQL so I just wanted to give a heads-up to anyone with more experience.

**Comment by r3pek** [comment]
Maybe it has something to do with this?
![image](https://cloud.githubusercontent.com/assets/3050556/18121160/292a1e36-6f5b-11e6-93e9-7a4eddbcfb4e.png)
The same spawnpoint have *way* too much spawns seconds appart. I had around 300 spawnpoints and now i'm at 1700+ for a 2km~ area which isn't normal.

**Comment by averylarry** [comment]
Could check to see if it's related to #1075

**Comment by Silvanus0** [comment]
@averylarry My issue was with the differing spawntimes specifically, however that's another case of a bad filter request. (The solution I found should fix that too actually)

@r3pek As I mentioned earlier it seems that is exactly what's going on. If you want to try out the solution I found below and let us know how it goes that would help! 

Go to your PokemonGo-Map folder then pogom>models.py open it up with Notepad++ and look for lines 234 and 259, around there you should see two instances of:

        if args.db_type == 'mysql':
            query = query.distinct(Pokemon.spawnpoint_id)
        else:
            query = query.group_by(Pokemon.spawnpoint_id)

Change the "distinct" to "group_by" at both locations so that it should look like this:

        if args.db_type == 'mysql':
            query = query.group_by(Pokemon.spawnpoint_id)
        else:
            query = query.group_by(Pokemon.spawnpoint_id)


Alternatively the if/else statement can be thrown away so that we just have:

        query = query.group_by(Pokemon.spawnpoint_id)

Any developers want to weigh in as to why the if/else is there in the first place? As in why is ".distinct" preferred? (I know SQLite can't support distinct)

**Comment by gabrielsoldani** [comment]
IIRC it's because group by won't work on MySQL if ONLY_FULL_GROUP_BY is set.

**Comment by gabrielsoldani** [comment]
By the way, this will be fixed once we keep a separate database for spawnpoints (since `spawnpoint_id` will be a primary key, which means each `spawnpoint_id` will have exactly one `time`).

**Comment by FrostTheFox** [comment]
closing due to -ss being obsolete
